# Generated by Django 4.1.7 on 2023-05-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Cart_id',
            new_name='cart_id',
        ),
    ]
