# Generated by Django 4.1.7 on 2023-04-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='ig',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='nam',
        ),
    ]
